# -*- coding: utf-8 -*-
"""Tugas 1 Kelompok 5 Compro ll

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ey-T5IjfhmQn4_F2Cl_VCbdTdKgNlGrW
"""

# Data mentah sesuai soal
data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

# Menampilkan data mentah terlebih dahulu
print(f"Data Mentah: '{data_kotor}'")

# Menghapus spasi di awal dan akhir string
data_bersih = data_kotor.strip()

# Menghapus karakter # pada string
data_bersih = data_bersih.replace("#", "")

# Memecah string berdasarkan tanda -
data_list = data_bersih.split("-")

# Mengambil masing-masing bagian data
id_pendaftar = data_list[0]
nama = data_list[1]
program_studi = data_list[2]
skill = data_list[3]
status = data_list[4]

# Mengubah nama menjadi format yang rapi
nama_list = nama.split()
nama_lengkap = nama_list[0].capitalize() + " " + nama_list[1].capitalize()

# Mengubah program studi menjadi huruf kapital
program_studi = program_studi.upper()

# Memecah skill berdasarkan tanda koma
skill_list = skill.split(",")

# Menggabungkan skill dengan tanda &
skill_dikuasai = " & ".join(skill_list)

# Menghitung panjang ID
panjang_id = len(id_pendaftar)

# Menghitung jumlah skill
total_skill = skill.count(",") + 1

# Mengubah status akun agar huruf depan kapital
status_akun = status.capitalize()

# Menampilkan hasil akhir
print("=====================================")
print("\tHASIL VERIFIKASI DATA")
print("=====================================")
print(f"ID Pendaftar   : {id_pendaftar} ({panjang_id} digit)")
print(f"Nama Lengkap   : {nama_lengkap}")
print(f"Program Studi  : {program_studi}")
print(f"Skill Dikuasai : {skill_dikuasai}")
print(f"Total Skill    : {total_skill}")
print(f"Status Akun    : {status_akun}")
print("=====================================")