# -*- coding: utf-8 -*-
"""Tugas 1 Kelompok 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ey-T5IjfhmQn4_F2Cl_VCbdTdKgNlGrW
"""

# Data mentah
data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

# Menampilkan data mentah
print(f"Data Mentah: '{data_kotor}'")

# Menghapus spasi di kiri dan kanan
data_bersih = data_kotor.strip()

# Menghapus tanda pagar
data_bersih = data_bersih.replace("#", "")

# Memecah data berdasarkan tanda -
data_split = data_bersih.split("-")

# Mengambil masing-masing data
id_pendaftar = data_split[0]
nama = data_split[1]
prodi = data_split[2]
skill = data_split[3]
status = data_split[4]

# Mengubah nama agar huruf awal kapital
nama = nama.title()

# Mengubah program studi menjadi huruf besar
prodi = prodi.upper()

# Memecah skill berdasarkan koma
list_skill = skill.split(",")

# Menggabungkan skill dengan tanda &
skill_final = " & ".join(list_skill)

# Menghitung panjang ID
panjang_id = len(id_pendaftar)

# Menghitung jumlah skill
jumlah_skill = skill.count(",") + 1

# Mengubah status agar huruf awal kapital
status = status.capitalize()

# Output akhir
print("=====================================")
print("\tHASIL VERIFIKASI DATA")
print("=====================================")
print(f"ID Pendaftar   : {id_pendaftar} ({panjang_id} digit)")
print(f"Nama Lengkap   : {nama}")
print(f"Program Studi  : {prodi}")
print(f"Skill Dikuasai : {skill_final}")
print(f"Total Skill    : {jumlah_skill}")
print(f"Status Akun    : {status}")
print("=====================================")